# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.8
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: pocockn
          POSTGRES_DB: crypto_compare_test
      
    working_directory: /go/src/github.com/pocockn/crypto-compare-go 
    steps:
      - checkout

      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...

  deployment:
    staging:
      branch: master
      heroku:
        appname: go-vidsy-project

    